#!/bin/bash -l
# This goes in the hooks folder of the bare git repo and is executed when
# changes are pushed.

# The path to the bare repo:
GIT_REPO=$HOME/elab_git_repo ;
# The path for a temporary clone we will create just long enough to use it to build the jekyll site:
TMP_GIT_CLONE=$HOME/TMP_elab_repo ;
# The path where the html will be written so apache can serve it:
ELAB_WWW=$HOME/elab_html ;

# make a temporary clone of the repo
git clone $GIT_REPO $TMP_GIT_CLONE ;
# cd into the clone
cd $TMP_GIT_CLONE ;
# Force git to forget the repo this hook is running from
unset GIT_DIR ;
# Build the jekyll site to the html folder
jekyll build --destination $ELAB_WWW ;
# cd out of the clone
cd $HOME ;
# Delete the clone
rm -rf $TMP_GIT_CLONE ;
exit ;
